services:
  open_notebook:
    image: lfnovo/open_notebook:latest-single
    ports:
      - "8502:8502"
      - "5055:5055"
    env_file:
      - ./docker.env  # <--- 使用 env_file 載入環境變數
    environment:
      - OLLAMA_API_BASE=http://192.168.200.162:11434
    volumes:
      - ./notebook_data:/app/data
      - ./surreal_data:/mydata
    restart: always
